build_from:
  aarch64: "opencloudeu/opencloud-rolling:latest"
  amd64: "opencloudeu/opencloud-rolling:latest"
  armhf: "opencloudeu/opencloud-rolling:latest"
  armv7: "opencloudeu/opencloud-rolling:latest"
  i386: "opencloudeu/opencloud-rolling:latest"
labels:
  org.opencontainers.image.title: "OpenCloud"
  org.opencontainers.image.description: "OpenCloud File Management & Collaboration"
  org.opencontainers.image.source: "https://github.com/d-shmt/ha-addons"
  org.opencontainers.image.licenses: "Apache-2.0"
args: {}
