#!/bin/bash
set -e

# Funktion für Log-Ausgaben
log() {
    echo "[$(date '+%H:%M:%S')] $1"
}

log "--> Starting OpenCloud Add-on Setup..."

# 1. Konfiguration auslesen
DOMAIN=$(jq --raw-output '.domain' $CONFIG_PATH)
STORAGE_PATH=$(jq --raw-output '.storage_path' $CONFIG_PATH)

log "--> Configuration loaded:"
log "    Domain: $DOMAIN"
log "    Storage: $STORAGE_PATH"

# 2. Prüfen des Speicherpfads
if [ ! -d "$STORAGE_PATH" ]; then
    log "CRITICAL ERROR: Storage path $STORAGE_PATH NOT found!"
    exit 1
fi

# 3. Environment Variablen setzen (Basics)
export OC_SERVER_ROOT="/data"
export OC_SERVER_ADDRESS="0.0.0.0"
export OC_SERVER_PORT="9200"
export OC_URL="https://$DOMAIN"
export OC_INSECURE="true"
export OC_STORAGE_LOCAL_ROOT="$STORAGE_PATH"
export OC_BASE_DATA_PATH="/data"
export OC_CONFIG_FILE="/data/opencloud.yaml"

# 4. Config-Initialisierung
if [ -f "/data/opencloud.yaml" ]; then
    log "--> Config file exists."
else
    log "--> No config found. Initializing..."
    opencloud init || true
fi

# 5. DIE MAGIE: Config neu schreiben
log "--> Re-writing config file to enforce Mount IDs..."

# Wir lesen die Secrets aus der existierenden Datei (die gerade von init erstellt wurde)
# Wir nutzen grep und cut, um den Wert hinter dem Doppelpunkt zu holen und Leerzeichen zu entfernen.
JWT_SECRET=$(grep "jwt_secret:" /data/opencloud.yaml | cut -d: -f2 | tr -d '[:space:]')
TRANSFER_SECRET=$(grep "transfer_secret:" /data/opencloud.yaml | cut -d: -f2 | tr -d '[:space:]')
MACHINE_AUTH=$(grep "machine_auth_api_key:" /data/opencloud.yaml | cut -d: -f2 | tr -d '[:space:]')
SYSTEM_USER_ID=$(grep "system_user_id:" /data/opencloud.yaml | cut -d: -f2 | tr -d '[:space:]')
ADMIN_USER_ID=$(grep "admin_user_id:" /data/opencloud.yaml | cut -d: -f2 | tr -d '[:space:]')

# Wir definieren unsere Mount IDs fest
MOUNT_ID_USERS="a0000000-0000-0000-0000-000000000001"
MOUNT_ID_SYSTEM="a0000000-0000-0000-0000-000000000002"

log "--> Secrets extracted. Creating clean config..."

# Wir überschreiben die Datei jetzt komplett mit einem sauberen YAML
cat > /data/opencloud.yaml <<EOF
---
# Auto-generated by Home Assistant Add-on
system_user_id: "$SYSTEM_USER_ID"
admin_user_id: "$ADMIN_USER_ID"
machine_auth_api_key: "$MACHINE_AUTH"
transfer_secret: "$TRANSFER_SECRET"

token_manager:
  jwt_secret: "$JWT_SECRET"

# Hier setzen wir die Mount IDs GLOBAL
storage_users_mount_id: "$MOUNT_ID_USERS"
storage_system_mount_id: "$MOUNT_ID_SYSTEM"

gateway:
  storage_users_mount_id: "$MOUNT_ID_USERS"
  storage_system_mount_id: "$MOUNT_ID_SYSTEM"

frontend:
  storage_users_mount_id: "$MOUNT_ID_USERS"

webdav:
  storage_users_mount_id: "$MOUNT_ID_USERS"

storage_users:
  mount_id: "$MOUNT_ID_USERS"

storage_system:
  mount_id: "$MOUNT_ID_SYSTEM"

auth_machine:
  api_key: "$MACHINE_AUTH"

# Wichtig: Log Level setzen
log:
  level: info
  pretty: false
  color: false

EOF

log "--> Config file rewritten successfully."
log "--> DEBUG: Checking file content:"
head -n 25 /data/opencloud.yaml

log "--> Starting OpenCloud Server..."
echo "------------------------------------------------"

# Starten
exec opencloud server
